# fly.toml app configuration file generated for image-generator-app
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "image-generator-app"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8000 # تعديل المنفذ الداخلي ليطابق إعدادات التطبيق
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80 # نشر الخدمة عبر المنفذ 80 لدعم HTTP
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443 # نشر الخدمة عبر المنفذ 443 لدعم HTTPS

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
