app = "image-generator-app"  # اسم التطبيق

[[services]]
internal_port = 8000  # البورت الداخلي
protocol = "tcp"  # تأكد أن البروتوكول هو TCP
force_https = true

[[services.ports]]
handlers = ["http"]
port = 80  # البورت الخارجي الافتراضي
